/* ============================================================
   OLOGENETICA · GLOSSÁRIO — PORTUGUÊS (BRASIL)
   · TERMS: termos que o leitor pode não conhecer.
     m = formas a reconhecer no texto (singular/plural/variantes,
         exatamente como aparecem nos textos DESTA língua)
     t = título do balão · d = explicação em linguagem do dia a dia
   · PP: as 64 Chaves «em palavras simples» — uma linha concreta cada.
   ============================================================ */
(function () {

  const TERMS = {
    chiave:    { m: ["Chave", "Chaves"], t: "Chave",
      d: "Uma das 64 «energias base» do sistema. Cada Chave corresponde a um hexagrama do I Ching e descreve um jeito de ser: do seu lado difícil (Sombra) ao seu talento (Dom)." },
    ombra:     { m: ["Sombra", "sombras"], t: "Sombra",
      d: "O lado reativo de uma Chave: como essa energia se comporta quando há medo ou estresse. Não é um defeito a eliminar — é o ponto de partida da leitura." },
    dono:      { m: ["Dom", "Dons"], t: "Dom",
      d: "O talento da Chave: exatamente a mesma energia da Sombra, só que vivida com consciência. A Sombra que relaxa vira Dom." },
    siddhi:    { m: ["Siddhi"], t: "Siddhi",
      d: "Palavra em sânscrito: o florescimento mais alto possível de uma Chave, o seu potencial pleno. Serve de estrela-guia — não é uma meta para «alcançar»." },
    linea:     { m: ["Linha", "Linhas"], t: "Linha",
      d: "Cada Chave se divide em 6 Linhas. Se a Chave é o «quê», a Linha é o «como»: estudando (1), por talento natural (2), por tentativa e erro (3), através das pessoas (4), resolvendo (5), ou com a visão do todo (6)." },
    sfera:     { m: ["esfera", "esferas"], t: "Esfera",
      d: "Uma área da sua vida: trabalho, relacionamentos, mente, prosperidade… O perfil tem 11, e em cada uma «cai» uma das 64 Chaves." },
    esagramma: { m: ["hexagrama", "hexagramas"], t: "Hexagrama",
      d: "Figura do I Ching formada por 6 linhas inteiras ou partidas. As combinações possíveis são 64: uma para cada Chave." },
    iching:    { m: ["I Ching"], t: "I Ching",
      d: "Antiquíssimo livro chinês de sabedoria, o «Livro das Mutações»: descreve 64 situações-tipo da vida através dos 64 hexagramas." },
    natale:    { m: ["natal", "personalidade", "Personalidade"], t: "Natal / Personalidade",
      d: "Calculado no momento exato do nascimento. É a sua parte consciente: aquela que você reconhece como «eu» e na qual se enxerga com facilidade." },
    design:    { m: ["design", "Design"], t: "Design",
      d: "Calculado cerca de 3 meses antes do nascimento (quando o Sol estava 88° mais atrás). É a sua parte inconsciente: age sozinha, antes de você decidir — muitas vezes é a que os outros veem melhor do que você." },
    sequenza:  { m: ["Sequência", "Sequências", "sequência", "sequências"], t: "Sequência",
      d: "Um roteiro de leitura: as 11 esferas se leem em três grupos. Ativação = o seu propósito, Vênus = o coração e os relacionamentos, Pérola = a prosperidade." },
    croce:     { m: ["Cruz de encarnação", "cruz de encarnação"], t: "Cruz de encarnação",
      d: "Os 4 números centrais do perfil: as Chaves de Sol e Terra, conscientes e inconscientes. É o «tema principal» da sua vida resumido em quatro energias." },
    specchio:  { m: ["parceiras de programação", "Chaves espelho", "Chave espelho", "espelho"], t: "Chaves espelho",
      d: "Cada Chave tem uma gêmea oposta na roda, a 180°. São duas metades do mesmo tema: o que falta em uma, a outra tem." },
    anello:    { m: ["anéis de códons", "anel de códons", "Anéis de códons"], t: "Anel de códons",
      d: "As 64 Chaves se agrupam em 21 «famílias» chamadas anéis, inspiradas no modo como os códons do DNA se agrupam por função. O vínculo com o DNA é simbólico, não científico." },
    codone:    { m: ["códons", "códon"], t: "Códons",
      d: "Os «tijolinhos» do código genético: trincas que formam 64 combinações possíveis — o mesmo número dos hexagramas. Daí o paralelo simbólico do sistema." },
    ritsolare: { m: ["retorno solar", "Retorno solar"], t: "Retorno solar",
      d: "O instante, perto do aniversário, em que o Sol volta exatamente à posição em que estava quando você nasceu. Usa-se para ler o tema do ano." },
    ritsaturno:{ m: ["retorno de Saturno", "1º retorno de Saturno", "2º retorno de Saturno"], t: "Retorno de Saturno",
      d: "Saturno leva ~29 anos para dar a volta completa e voltar aonde estava no seu nascimento. Por volta dos 29 e dos 59 anos: tradicionalmente duas grandes passagens de amadurecimento." },
    transito:  { m: ["trânsitos", "trânsito", "transita"], t: "Trânsito",
      d: "Onde os planetas estão agora, comparado com o seu perfil. Quando um planeta «passa» por uma Chave sua, aquele tema se acende por alguns dias." },
    effemeridi:{ m: ["efemérides", "Efemérides"], t: "Efemérides",
      d: "As tabelas astronômicas com as posições exatas dos planetas, momento a momento. As mesmas que os observatórios usam: aqui nada é inventado, as posições são reais." },
    arco:      { m: ["88° de arco solar", "arco solar"], t: "Arco solar",
      d: "O trecho de círculo que o Sol percorre no céu visto da Terra. 88° correspondem a cerca de 3 meses de caminhada." },
    ruota:     { m: ["roda zodiacal", "roda dos 64"], t: "A roda",
      d: "O círculo de 360° do zodíaco, dividido em 64 setores iguais: um por Chave. A posição de um planeta no círculo diz em qual Chave ele está." },
    qi:        { m: ["IQ"], t: "IQ — o ciclo da mente",
      d: "A esfera formada entre os 14 e os 21 anos: como a sua mente aprendeu a pensar e a se defender na adolescência. Adulto, você a confunde com «o meu jeito de raciocinar»." },
    qe:        { m: ["EQ"], t: "EQ — o ciclo do coração",
      d: "A esfera formada entre os 7 e os 14 anos: como o seu coração aprendeu a reagir quando criança. É a defesa emocional que hoje dispara sozinha." },
    qs:        { m: ["SQ"], t: "SQ — a raiz da confiança",
      d: "A esfera dos primeiros 7 anos de vida: a marca mais profunda, onde se decidiu o quanto dá para confiar no amor. Também chamada de «Ponto de Amor»." },
    lifework:  { m: ["Life's Work"], t: "Life's Work",
      d: "«A obra da vida»: aquilo que você veio fazer, o papel que o mundo vê em você. É a esfera principal do perfil." },
    evolution: { m: ["Evolution"], t: "Evolution",
      d: "O seu desafio central: o tema que a vida traz de volta para fazer você crescer. Não é um defeito — é um caminho." },
    radiance:  { m: ["Radiance"], t: "Radiance",
      d: "O que acende a sua vitalidade e saúde: quando você vive isso, dá para ver — literalmente — na energia que você irradia." },
    purposeT:  { m: ["Purpose"], t: "Purpose",
      d: "O seu propósito profundo: ele se ativa quando o que você faz serve a algo maior do que você." },
    attraction:{ m: ["Attraction"], t: "Attraction",
      d: "Quem e o que você atrai nos relacionamentos: a porta de entrada dos seus vínculos." },
    core:      { m: ["Core", "Vocation"], t: "Core / Vocation",
      d: "A ferida mais antiga (Core) que, uma vez atravessada, vira a sua vocação (Vocation): o ponto onde a dor se transforma em ofício da alma." },
    culture:   { m: ["Culture"], t: "Culture",
      d: "O seu lugar natural na comunidade: a contribuição que você traz quando está em um grupo." },
    pearl:     { m: ["Pearl", "Brand"], t: "Pearl / Brand",
      d: "A Pérola é a recompensa: a prosperidade que chega quando você simplifica. O Brand é como o mundo reconhece você — o Life's Work visto de fora." },
    ics:       { m: ["ICS", "arquivo ICS"], t: "Arquivo ICS",
      d: "O formato padrão dos calendários: você baixa o arquivo, abre, e os eventos aparecem no seu calendário (Google Agenda, Apple, Outlook…)." }
  };

  // As 64 Chaves em palavras simples: uma linha concreta, do dia a dia
  const PP = {
    1:  "Você tem dias em que não cria nada: deixe-os passar em vez de brigar com eles, e você volta com ideias frescas.",
    2:  "Você sabe por instinto que direção tomar: confie nessa bússola em vez de pedir confirmação a todo mundo.",
    3:  "No começo você faz bagunça, depois encontra soluções que ninguém tinha visto: a desordem é a sua matéria-prima.",
    4:  "Você quer uma explicação para tudo: ótimo, desde que não exija que a sua seja a única certa.",
    5:  "Você se irrita quando as coisas não andam no seu ritmo: a vida tem o dela, e costuma acertar.",
    6:  "Você sente na hora a tensão no ar: pode usá-la para brigar ou para apaziguar.",
    7:  "As pessoas seguem você quando você aponta o caminho sem dar ordens.",
    8:  "Você faz as coisas do seu jeito: quando se uniformiza para não chamar atenção, apaga a sua melhor parte.",
    9:  "Você se perde nos detalhes errados ou adia: escolha um detalhe certo e insista ali.",
    10: "Pare de interpretar um personagem: quando você é simplesmente você, as coisas se ajeitam sozinhas.",
    11: "Sua cabeça vive cheia de ideias e imagens: você não precisa realizar todas — muitas são para contar.",
    12: "Fale menos e nos momentos certos: uma frase sua dita na hora certa vale ouro.",
    13: "As pessoas contam os segredos delas para você: escute sem carregar o peso.",
    14: "O dinheiro chega quando você trabalha no que ama, não quando aperta os dentes num trabalho que detesta.",
    15: "Você vive em ondas: dias cheíssimos e dias vazios. É o seu ritmo normal, não um defeito.",
    16: "Você se empolga com mil coisas: escolha uma e repita até virar arte.",
    17: "Você vê onde as coisas vão dar antes dos outros: ofereça a previsão, sem impor.",
    18: "Você nota na hora o que está errado: use isso para consertar, não para criticar (você incluso).",
    19: "Você sente as necessidades dos outros antes que falem: ajude sem se tornar indispensável.",
    20: "Você é bom em agir no impulso certo: faça isso quando for preciso, não para preencher o silêncio.",
    21: "Você precisa estar no controle: funciona com as coisas, sufoca com as pessoas. Aprenda a delegar de verdade.",
    22: "Mesmo com tempestade por dentro, você consegue continuar gentil: é a sua magia — não a desperdice em explosões.",
    23: "Você sabe explicar coisas complicadas de um jeito simples: diga em uma frase e pare por aí.",
    24: "Você rumina em loop: a virada vem na pausa, não na próxima volta.",
    25: "As feridas foram fechando o seu coração aos poucos: cada vez que você aceita o que existe, um pedaço reabre.",
    26: "Você sabe se vender e vender: use isso para coisas em que acredita, não para inflar a imagem.",
    27: "Você cuida de todo mundo: ótimo — mas sem manter a conta dos favores.",
    28: "Você prefere arriscar a se arrepender: só escolha as apostas que valem de verdade.",
    29: "Quando disser sim, diga inteiro: os sins pela metade esvaziam você.",
    30: "Você deseja com força total: aproveite o fogo sem esperar que o que deseja salve a sua vida.",
    31: "Quando você fala, o grupo escuta: diga o que todos sentem mas ninguém formula.",
    32: "O medo de fracassar faz você segurar tudo: separe o que deve ser guardado do que deve ser solto.",
    33: "Depois de experiências fortes você precisa se recolher: é ali que você entende — e depois conte.",
    34: "Você tem energia de sobra: use-a no seu caminho, não para provar algo a alguém.",
    35: "Você quer experimentar tudo: escolha as experiências que ensinam, não as que só tapam o tédio.",
    36: "Você atravessa tempestades emocionais: cada crise superada faz de você a pessoa que entende os outros.",
    37: "Você é a cola da família ou do grupo: combinados claros e afeto, sem engolir sapo por paz de fachada.",
    38: "Você é um lutador nato: escolha as batalhas que valem, não todas.",
    39: "Você sabe cutucar onde é preciso: provoque para destravar, não para irritar.",
    40: "Você trabalha duro e depois desaba: aprenda a dizer não a tempo, sem mágoa.",
    41: "Você sonha sempre com um novo começo: transforme um em fato, e deixe o resto sonhar.",
    42: "Você tem dificuldade de fechar capítulos: cada final bem fechado libera você para o próximo começo.",
    43: "Você tem intuições fora do coro: traduza-as em palavras compreensíveis, ou ficarão sem ouvidos.",
    44: "Você entende as pessoas no primeiro olhar: coloque cada uma no papel certo, sem manipular.",
    45: "Você é um líder de bando natural: guie distribuindo, não acumulando.",
    46: "As coisas dão certo quando você habita o seu corpo: escute-o, em vez de viver só de cabeça.",
    47: "Lembranças pesadas ficam rodando na sua cabeça: com o tempo viram a sua profundidade — deixe-as amadurecer.",
    48: "Você sempre se sente não pronto o bastante: aja assim mesmo — a sua profundidade aparece sob pressão.",
    49: "Você tende a cortar pontes por impulso: faça as revoluções na hora certa, levando junto quem topar.",
    50: "Você carrega a responsabilidade de todos: cuide do que importa sem se esmagar.",
    51: "Você é o primeiro a ousar: a sua coragem abre caminhos — depois volte para contar que dá.",
    52: "Você vibra de energia contida: concentre-a num ponto só e solte o resto.",
    53: "Você começa mil coisas: nem todas cabem a você terminar — mas leve uma até o fim.",
    54: "Você é ambicioso: a vontade de subir é saudável quando você sobe de nível, não só de quantidade.",
    55: "Seu humor vai em ondas: surfe nelas em vez de culpar o que está fora. Humor é clima, não identidade.",
    56: "Você se distrai com mil estímulos: transforme-os em histórias e eles viram riqueza para todos.",
    57: "Você sente as coisas um instante antes dos outros: esse instinto sutil quase sempre tem razão — escute-o na hora.",
    58: "Você sempre vê o que dá para melhorar: conserte com alegria, em vez de reclamar do defeito.",
    59: "Você vai direto à intimidade: sem estratégias você funciona melhor — a transparência desarma.",
    60: "Limites apertam você: aceite a forma deles, e dentro dessa forma você fica criativo.",
    61: "Você busca respostas para as grandes perguntas: aprenda a amar a pergunta — os lampejos chegam sozinhos.",
    62: "Você é preciso ao extremo: diga exatamente o que é preciso, não tudo o que sabe.",
    63: "Você duvida de tudo: transforme as suspeitas em perguntas precisas e verificações, não em cismas.",
    64: "Sua cabeça vive cheia de imagens buscando um sentido: pare de forçar — o quadro se monta sozinho."
  };

  window.HOLO_GLOSS = window.HOLO_GLOSS || {};
  window.HOLO_GLOSS.pt = { ppLbl: "Em palavras simples", TERMS, PP };
})();
