/* ============================================================
   OLOGENETICA · GLOSSARIO — ITALIANO (master)
   · TERMS: termini che il lettore può non conoscere.
     m = forme da riconoscere nel testo (singolare/plurale/varianti,
         così come compaiono nei testi di QUESTA lingua)
     t = titolo del fumetto · d = spiegazione in linguaggio quotidiano
   · PP: le 64 Chiavi «in parole povere» — una riga concreta ciascuna.
   Le traduzioni devono ADATTARE le forme m alla propria lingua.
   ============================================================ */
(function () {

  const TERMS = {
    chiave:    { m: ["Chiave", "Chiavi"], t: "Chiave",
      d: "Una delle 64 «energie base» del sistema. Ogni Chiave corrisponde a un esagramma dell'I Ching e descrive un modo di essere: dal suo lato difficile (Ombra) al suo talento (Dono)." },
    ombra:     { m: ["Ombra", "ombre"], t: "Ombra",
      d: "Il lato reattivo di una Chiave: come si comporta quell'energia quando c'è paura o stress. Non è un difetto da eliminare — è il punto di partenza della lettura." },
    dono:      { m: ["Dono", "Doni"], t: "Dono",
      d: "Il talento della Chiave: la stessa identica energia dell'Ombra, vissuta però con consapevolezza. L'Ombra che si rilassa diventa Dono." },
    siddhi:    { m: ["Siddhi"], t: "Siddhi",
      d: "Parola sanscrita: la fioritura più alta possibile di una Chiave, il suo potenziale pieno. Serve da stella polare — non è un obiettivo da «raggiungere»." },
    linea:     { m: ["Linea", "Linee"], t: "Linea",
      d: "Ogni Chiave si divide in 6 Linee. Se la Chiave è il «cosa», la Linea è il «come»: studiando (1), per talento naturale (2), per tentativi (3), attraverso le persone (4), risolvendo (5), o con la visione d'insieme (6)." },
    sfera:     { m: ["sfera", "sfere"], t: "Sfera",
      d: "Un'area della tua vita: lavoro, relazioni, mente, prosperità… Il profilo ne ha 11, e in ognuna «cade» una delle 64 Chiavi." },
    esagramma: { m: ["esagramma", "esagrammi"], t: "Esagramma",
      d: "Figura dell'I Ching composta da 6 linee intere o spezzate. Le combinazioni possibili sono 64: una per ogni Chiave." },
    iching:    { m: ["I Ching"], t: "I Ching",
      d: "Antichissimo libro cinese di saggezza, il «Libro dei Mutamenti»: descrive 64 situazioni-tipo della vita attraverso i 64 esagrammi." },
    natale:    { m: ["natale", "personalità", "Personalità"], t: "Natale / Personalità",
      d: "Calcolato sul momento esatto della nascita. È la tua parte consapevole: quella che riconosci come «io» e in cui ti riconosci facilmente." },
    design:    { m: ["design", "Design"], t: "Design",
      d: "Calcolato circa 3 mesi prima della nascita (quando il Sole era 88° più indietro). È la tua parte inconscia: agisce da sola, prima che tu decida — spesso è quella che gli altri vedono meglio di te." },
    sequenza:  { m: ["Sequenza", "Sequenze", "sequenza", "sequenze"], t: "Sequenza",
      d: "Un percorso di lettura: le 11 sfere si leggono in tre gruppi. Attivazione = il tuo scopo, Venere = il cuore e le relazioni, Perla = la prosperità." },
    croce:     { m: ["Croce d'incarnazione", "croce d'incarnazione"], t: "Croce d'incarnazione",
      d: "I 4 numeri centrali del profilo: le Chiavi di Sole e Terra, consce e inconsce. È il «tema portante» della tua vita riassunto in quattro energie." },
    specchio:  { m: ["partner di programmazione", "Chiavi specchio", "Chiave specchio", "specchio"], t: "Chiavi specchio",
      d: "Ogni Chiave ha una gemella opposta sulla ruota, a 180°. Sono due metà dello stesso tema: quello che manca a una, ce l'ha l'altra." },
    anello:    { m: ["anelli di codoni", "anello di codoni", "Anelli di codoni"], t: "Anello di codoni",
      d: "Le 64 Chiavi si raggruppano in 21 «famiglie» chiamate anelli, ispirate al modo in cui i codoni del DNA si raggruppano per funzione. Il legame col DNA è simbolico, non scientifico." },
    codone:    { m: ["codoni", "codone"], t: "Codoni",
      d: "I «mattoncini» del codice genetico: triplette che formano 64 combinazioni possibili — lo stesso numero degli esagrammi. Da qui il parallelo simbolico del sistema." },
    ritsolare: { m: ["ritorno solare", "Ritorno solare"], t: "Ritorno solare",
      d: "L'istante, vicino al compleanno, in cui il Sole torna esattamente nella posizione in cui era quando sei nato. Si usa per leggere il tema dell'anno." },
    ritsaturno:{ m: ["ritorno di Saturno", "1º ritorno di Saturno", "2º ritorno di Saturno"], t: "Ritorno di Saturno",
      d: "Saturno impiega ~29 anni a fare il giro completo e tornare dov'era alla tua nascita. Verso i 29 e i 59 anni: tradizionalmente due grandi passaggi di maturazione." },
    transito:  { m: ["transiti", "transito", "transita"], t: "Transito",
      d: "Dove si trovano i pianeti adesso, confrontato col tuo profilo. Quando un pianeta «passa» su una tua Chiave, quel tema si accende per qualche giorno." },
    effemeridi:{ m: ["effemeridi", "Effemeridi"], t: "Effemeridi",
      d: "Le tabelle astronomiche con le posizioni esatte dei pianeti, momento per momento. Le stesse che usano gli osservatori: qui niente è inventato, le posizioni sono vere." },
    arco:      { m: ["88° di arco solare", "arco solare"], t: "Arco solare",
      d: "Il tratto di cerchio che il Sole percorre nel cielo visto dalla Terra. 88° corrispondono a circa 3 mesi di cammino." },
    ruota:     { m: ["ruota zodiacale", "ruota dei 64"], t: "La ruota",
      d: "Il cerchio dei 360° dello zodiaco, diviso in 64 settori uguali: uno per Chiave. La posizione di un pianeta sul cerchio dice in quale Chiave si trova." },
    qi:        { m: ["IQ"], t: "IQ — il ciclo della mente",
      d: "La sfera formata tra i 14 e i 21 anni: come la tua mente ha imparato a pensare e a difendersi nell'adolescenza. Da adulto la scambi per «il mio modo di ragionare»." },
    qe:        { m: ["EQ"], t: "EQ — il ciclo del cuore",
      d: "La sfera formata tra i 7 e i 14 anni: come il tuo cuore ha imparato a reagire da bambino. È la difesa emotiva che oggi scatta da sola." },
    qs:        { m: ["SQ"], t: "SQ — la radice della fiducia",
      d: "La sfera dei primi 7 anni di vita: l'impronta più profonda, dove si è deciso quanto ci si può fidare dell'amore. Detta anche «Punto d'Amore»." },
    lifework:  { m: ["Life's Work"], t: "Life's Work",
      d: "«Il lavoro della vita»: ciò che sei venuto a fare, il ruolo che il mondo vede in te. È la sfera principale del profilo." },
    evolution: { m: ["Evolution"], t: "Evolution",
      d: "La tua sfida centrale: il tema che la vita ti ripropone per farti crescere. Non un difetto — un percorso." },
    radiance:  { m: ["Radiance"], t: "Radiance",
      d: "Ciò che accende la tua vitalità e salute: quando lo vivi, si vede — letteralmente — dall'energia che irradi." },
    purposeT:  { m: ["Purpose"], t: "Purpose",
      d: "Il tuo scopo profondo: si attiva quando quello che fai serve qualcosa di più grande di te." },
    attraction:{ m: ["Attraction"], t: "Attraction",
      d: "Chi e che cosa attiri nelle relazioni: la porta d'ingresso dei tuoi legami." },
    core:      { m: ["Core", "Vocation"], t: "Core / Vocation",
      d: "La ferita più antica (Core) che, una volta attraversata, diventa la tua vocazione (Vocation): il punto dove il dolore si trasforma in mestiere dell'anima." },
    culture:   { m: ["Culture"], t: "Culture",
      d: "Il tuo posto naturale nella comunità: il contributo che porti quando stai in un gruppo." },
    pearl:     { m: ["Pearl", "Brand"], t: "Pearl / Brand",
      d: "La Perla è la ricompensa: la prosperità che arriva quando semplifichi. Il Brand è come il mondo ti riconosce — il Life's Work visto da fuori." },
    ics:       { m: ["ICS", "file ICS"], t: "File ICS",
      d: "Il formato standard dei calendari: scaricato il file, lo apri e gli eventi compaiono nel tuo calendario (Google Calendar, Apple, Outlook…)." }
  };

  // Le 64 Chiavi in parole povere: una riga concreta, quotidiana
  const PP = {
    1:  "Hai momenti no in cui non crei niente: lasciali passare invece di combatterli, e torni con idee fresche.",
    2:  "Sai istintivamente che direzione prendere: fidati di quella bussola invece di chiedere conferme a tutti.",
    3:  "All'inizio fai confusione, poi trovi soluzioni che nessuno aveva visto: il disordine è la tua materia prima.",
    4:  "Vuoi una spiegazione per tutto: ottimo, finché non pretendi che la tua sia l'unica giusta.",
    5:  "Ti innervosisci se le cose non vanno ai tuoi tempi: la vita ha i suoi, e di solito ci azzecca.",
    6:  "Senti subito la tensione nell'aria: puoi usarla per litigare o per fare da paciere.",
    7:  "La gente ti segue quando indichi la strada senza dare ordini.",
    8:  "Fai le cose a modo tuo: quando ti uniformi per non dare nell'occhio, spegni il tuo pezzo migliore.",
    9:  "Ti perdi nei dettagli sbagliati o rimandi: scegli un dettaglio giusto e insisti lì.",
    10: "Smetti di recitare un personaggio: quando sei semplicemente te, le cose si sistemano da sole.",
    11: "Hai la testa piena di idee e immagini: non devi realizzarle tutte — molte sono da raccontare.",
    12: "Parla meno e nei momenti giusti: una tua frase detta al momento giusto vale oro.",
    13: "La gente ti racconta i suoi segreti: ascolta senza fartene carico.",
    14: "I soldi arrivano quando lavori a ciò che ami, non quando stringi i denti in un lavoro che detesti.",
    15: "Vivi a ondate: giorni pienissimi e giorni vuoti. È il tuo ritmo normale, non un guasto.",
    16: "Ti entusiasmi per mille cose: scegline una e ripetila finché diventa arte.",
    17: "Vedi dove andranno a finire le cose prima degli altri: offri la previsione, senza imporla.",
    18: "Noti subito cosa non va: usalo per aggiustare, non per criticare (te compreso).",
    19: "Senti i bisogni degli altri prima che parlino: aiuta senza renderti indispensabile.",
    20: "Sei bravo ad agire al volo: fallo quando serve, non per riempire il silenzio.",
    21: "Hai bisogno di avere il controllo: funziona sulle cose, soffoca sulle persone. Impara a delegare davvero.",
    22: "Anche quando dentro è tempesta riesci a restare gentile: è la tua magia — non sprecarla nelle sfuriate.",
    23: "Sai spiegare cose complicate in modo semplice: dilla in una frase e fermati lì.",
    24: "Rimugini in loop: la svolta arriva nella pausa, non nel giro successivo.",
    25: "Le ferite ti hanno chiuso il cuore a rate: ogni volta che accetti quello che c'è, se ne riapre un pezzo.",
    26: "Sai venderti e vendere: usalo per cose in cui credi, non per gonfiare l'immagine.",
    27: "Ti prendi cura di tutti: bene — ma senza tenere il conto dei favori.",
    28: "Preferisci rischiare che pentirti: scegli però solo le poste che valgono davvero.",
    29: "Quando dici sì, dillo tutto intero: i sì a metà ti svuotano.",
    30: "Desideri fortissimo: goditi il fuoco senza aspettarti che ciò che desideri ti salvi la vita.",
    31: "Quando parli, il gruppo ascolta: di' quello che tutti sentono ma nessuno formula.",
    32: "La paura di fallire ti fa trattenere tutto: distingui ciò che va conservato da ciò che va lasciato andare.",
    33: "Dopo le esperienze forti hai bisogno di ritirarti: è lì che capisci — e poi racconta.",
    34: "Hai energia da vendere: usala per la tua strada, non per dimostrare qualcosa a qualcuno.",
    35: "Vuoi provare tutto: scegli le esperienze che insegnano, non quelle che riempiono la noia.",
    36: "Attraversi tempeste emotive: ogni crisi superata ti rende la persona che capisce gli altri.",
    37: "Sei il collante della famiglia o del gruppo: patti chiari e affetto, senza ingoiare rospi per quieto vivere.",
    38: "Sei un combattente nato: scegli le battaglie che valgono, non tutte.",
    39: "Sai pungere dove serve: provoca per sbloccare, non per irritare.",
    40: "Lavori sodo e poi crolli: impara a dire no in tempo, senza rancore.",
    41: "Sogni sempre un nuovo inizio: trasformane uno in un fatto, il resto lascialo sognare.",
    42: "Fatichi a chiudere i capitoli: ogni fine ben chiusa ti libera per l'inizio successivo.",
    43: "Hai intuizioni fuori dal coro: traducile in parole comprensibili, o resteranno inascoltate.",
    44: "Capisci le persone al primo sguardo: mettile nel ruolo giusto, senza manovrarle.",
    45: "Sei un capobranco naturale: guida distribuendo, non accumulando.",
    46: "Ti va bene quando abiti il tuo corpo: ascoltalo, invece di vivere solo di testa.",
    47: "I ricordi pesanti ti girano in testa: col tempo diventano la tua profondità — lasciali maturare.",
    48: "Ti senti sempre non abbastanza pronto: agisci lo stesso — la tua profondità esce sotto pressione.",
    49: "Tendi a tagliare i ponti d'impulso: fai le rivoluzioni al momento giusto, portando con te chi ci sta.",
    50: "Ti carichi le responsabilità di tutti: custodisci ciò che conta senza schiacciarti.",
    51: "Sei il primo che osa: il tuo coraggio apre strade — poi torna a raccontare che si può.",
    52: "Vibri di energia trattenuta: concentrala su un punto solo e lascia andare il resto.",
    53: "Inizi mille cose: non tutte toccano a te da finire — ma una portala fino in fondo.",
    54: "Sei ambizioso: la spinta a salire è sana quando sali di livello, non solo di quantità.",
    55: "Il tuo umore va a onde: cavalcale invece di dare la colpa a ciò che sta fuori. L'umore è meteo, non identità.",
    56: "Ti distrai con mille stimoli: trasformali in racconti e diventano ricchezza per tutti.",
    57: "Senti le cose un attimo prima degli altri: quell'istinto sottile ha quasi sempre ragione — ascoltalo subito.",
    58: "Vedi sempre cosa si può migliorare: aggiusta con gioia, invece di lamentare il difetto.",
    59: "Vai dritto all'intimità: senza strategie funzioni meglio — la trasparenza disarma.",
    60: "I limiti ti stanno stretti: accettane la forma, e dentro quella forma diventi creativo.",
    61: "Cerchi risposte alle grandi domande: impara ad amare la domanda — i lampi arrivano da soli.",
    62: "Sei precisissimo: di' esattamente ciò che serve, non tutto ciò che sai.",
    63: "Dubiti di tutto: trasforma i sospetti in domande precise e verifiche, non in tarli.",
    64: "Hai la testa piena di immagini che cercano un senso: smetti di forzare — il quadro si compone da solo."
  };

  window.HOLO_GLOSS = window.HOLO_GLOSS || {};
  window.HOLO_GLOSS.it = { ppLbl: "In parole povere", TERMS, PP };
})();
