/* ============================================================
   OLOGENETICA · GLOSSAIRE — FRANÇAIS
   · TERMS : termes que le lecteur peut ne pas connaître.
     m = formes à reconnaître dans le texte (singulier/pluriel/variantes,
         telles qu'elles apparaissent dans les textes de CETTE langue)
     t = titre de la bulle · d = explication en langage de tous les jours
   · PP : les 64 Clés « en termes simples » — une ligne concrète chacune.
   ============================================================ */
(function () {

  const TERMS = {
    chiave:    { m: ["Clé", "Clés"], t: "Clé",
      d: "Une des 64 « énergies de base » du système. Chaque Clé correspond à un hexagramme du Yi King et décrit une façon d'être : de son côté difficile (l'Ombre) à son talent (le Don)." },
    ombra:     { m: ["Ombre", "ombres"], t: "Ombre",
      d: "Le côté réactif d'une Clé : comment cette énergie se comporte quand il y a de la peur ou du stress. Ce n'est pas un défaut à éliminer — c'est le point de départ de la lecture." },
    dono:      { m: ["Don", "Dons"], t: "Don",
      d: "Le talent de la Clé : exactement la même énergie que l'Ombre, mais vécue en conscience. L'Ombre qui se détend devient Don." },
    siddhi:    { m: ["Siddhi"], t: "Siddhi",
      d: "Mot sanskrit : l'épanouissement le plus haut possible d'une Clé, son plein potentiel. Il sert d'étoile polaire — ce n'est pas un objectif à « atteindre »." },
    linea:     { m: ["Ligne", "Lignes"], t: "Ligne",
      d: "Chaque Clé se divise en 6 Lignes. Si la Clé est le « quoi », la Ligne est le « comment » : en étudiant (1), par talent naturel (2), par essais-erreurs (3), à travers les gens (4), en résolvant (5), ou avec la vue d'ensemble (6)." },
    sfera:     { m: ["sphère", "sphères"], t: "Sphère",
      d: "Un domaine de ta vie : travail, relations, mental, prospérité… Le profil en compte 11, et dans chacune « tombe » une des 64 Clés." },
    esagramma: { m: ["hexagramme", "hexagrammes"], t: "Hexagramme",
      d: "Figure du Yi King composée de 6 traits pleins ou brisés. Il existe 64 combinaisons possibles : une par Clé." },
    iching:    { m: ["Yi King"], t: "Yi King",
      d: "Très ancien livre de sagesse chinois, le « Livre des Mutations » : il décrit 64 situations types de la vie à travers les 64 hexagrammes." },
    natale:    { m: ["natal", "personnalité", "Personnalité"], t: "Natal / Personnalité",
      d: "Calculé sur l'instant exact de ta naissance. C'est ta part consciente : celle que tu reconnais comme « moi » et dans laquelle tu te retrouves facilement." },
    design:    { m: ["design", "Design"], t: "Design",
      d: "Calculé environ 3 mois avant la naissance (quand le Soleil était 88° en arrière). C'est ta part inconsciente : elle agit toute seule, avant que tu ne décides — souvent, les autres la voient mieux que toi." },
    sequenza:  { m: ["Séquence", "Séquences", "séquence", "séquences"], t: "Séquence",
      d: "Un parcours de lecture : les 11 sphères se lisent en trois groupes. Activation = ton but, Vénus = le cœur et les relations, Perle = la prospérité." },
    croce:     { m: ["Croix d'incarnation", "croix d'incarnation"], t: "Croix d'incarnation",
      d: "Les 4 nombres centraux du profil : les Clés du Soleil et de la Terre, conscientes et inconscientes. C'est le « thème porteur » de ta vie résumé en quatre énergies." },
    specchio:  { m: ["partenaires de programmation", "Clés miroir", "Clé miroir", "miroir"], t: "Clés miroir",
      d: "Chaque Clé a une jumelle opposée sur la roue, à 180°. Ce sont deux moitiés du même thème : ce qui manque à l'une, l'autre l'a." },
    anello:    { m: ["anneaux de codons", "anneau de codons", "Anneaux de codons"], t: "Anneau de codons",
      d: "Les 64 Clés se regroupent en 21 « familles » appelées anneaux, inspirées de la façon dont les codons de l'ADN se regroupent par fonction. Le lien avec l'ADN est symbolique, pas scientifique." },
    codone:    { m: ["codons", "codon"], t: "Codons",
      d: "Les « briques » du code génétique : des triplets qui forment 64 combinaisons possibles — le même nombre que les hexagrammes. D'où le parallèle symbolique du système." },
    ritsolare: { m: ["retour solaire", "Retour solaire"], t: "Retour solaire",
      d: "L'instant, proche de ton anniversaire, où le Soleil revient exactement à la position qu'il occupait à ta naissance. On l'utilise pour lire le thème de l'année." },
    ritsaturno:{ m: ["retour de Saturne", "1er retour de Saturne", "2e retour de Saturne"], t: "Retour de Saturne",
      d: "Saturne met environ 29 ans à faire le tour complet et à revenir là où il était à ta naissance. Vers 29 et 59 ans : traditionnellement deux grands passages de maturation." },
    transito:  { m: ["transits", "transit", "transite"], t: "Transit",
      d: "Là où se trouvent les planètes en ce moment, comparé à ton profil. Quand une planète « passe » sur une de tes Clés, ce thème s'allume pendant quelques jours." },
    effemeridi:{ m: ["éphémérides", "Éphémérides"], t: "Éphémérides",
      d: "Les tables astronomiques avec les positions exactes des planètes, instant par instant. Les mêmes qu'utilisent les observatoires : ici rien n'est inventé, les positions sont réelles." },
    arco:      { m: ["88° d'arc solaire", "arc solaire"], t: "Arc solaire",
      d: "La portion de cercle que le Soleil parcourt dans le ciel vu depuis la Terre. 88° correspondent à environ 3 mois de chemin." },
    ruota:     { m: ["roue zodiacale", "roue des 64"], t: "La roue",
      d: "Le cercle des 360° du zodiaque, divisé en 64 secteurs égaux : un par Clé. La position d'une planète sur le cercle dit dans quelle Clé elle se trouve." },
    qi:        { m: ["IQ"], t: "IQ — le cycle du mental",
      d: "La sphère formée entre 14 et 21 ans : comment ton mental a appris à penser et à se défendre à l'adolescence. Adulte, tu la prends pour « ma façon de raisonner »." },
    qe:        { m: ["EQ"], t: "EQ — le cycle du cœur",
      d: "La sphère formée entre 7 et 14 ans : comment ton cœur a appris à réagir quand tu étais enfant. C'est la défense émotionnelle qui aujourd'hui se déclenche toute seule." },
    qs:        { m: ["SQ"], t: "SQ — la racine de la confiance",
      d: "La sphère des 7 premières années de vie : l'empreinte la plus profonde, là où s'est décidé à quel point on peut faire confiance à l'amour. On l'appelle aussi « Point d'Amour »." },
    lifework:  { m: ["Life's Work"], t: "Life's Work",
      d: "« L'œuvre de ta vie » : ce que tu es venu faire, le rôle que le monde voit en toi. C'est la sphère principale du profil." },
    evolution: { m: ["Evolution"], t: "Evolution",
      d: "Ton défi central : le thème que la vie te représente pour te faire grandir. Pas un défaut — un chemin." },
    radiance:  { m: ["Radiance"], t: "Radiance",
      d: "Ce qui allume ta vitalité et ta santé : quand tu le vis, ça se voit — littéralement — à l'énergie que tu rayonnes." },
    purposeT:  { m: ["Purpose"], t: "Purpose",
      d: "Ton but profond : il s'active quand ce que tu fais sert quelque chose de plus grand que toi." },
    attraction:{ m: ["Attraction"], t: "Attraction",
      d: "Qui et quoi tu attires dans tes relations : la porte d'entrée de tes liens." },
    core:      { m: ["Core", "Vocation"], t: "Core / Vocation",
      d: "La blessure la plus ancienne (Core) qui, une fois traversée, devient ta vocation (Vocation) : le point où la douleur se transforme en métier de l'âme." },
    culture:   { m: ["Culture"], t: "Culture",
      d: "Ta place naturelle dans la communauté : la contribution que tu apportes quand tu fais partie d'un groupe." },
    pearl:     { m: ["Pearl", "Brand"], t: "Pearl / Brand",
      d: "La Perle est la récompense : la prospérité qui arrive quand tu simplifies. Le Brand est la façon dont le monde te reconnaît — le Life's Work vu de l'extérieur." },
    ics:       { m: ["ICS", "fichier ICS"], t: "Fichier ICS",
      d: "Le format standard des calendriers : une fois le fichier téléchargé, tu l'ouvres et les événements apparaissent dans ton calendrier (Google Calendar, Apple, Outlook…)." }
  };

  // Les 64 Clés en termes simples : une ligne concrète, quotidienne
  const PP = {
    1:  "Tu as des passages à vide où tu ne crées rien : laisse-les passer au lieu de les combattre, et tu reviens avec des idées fraîches.",
    2:  "Tu sais d'instinct quelle direction prendre : fie-toi à cette boussole au lieu de demander confirmation à tout le monde.",
    3:  "Au début tu mets la pagaille, puis tu trouves des solutions que personne n'avait vues : le désordre est ta matière première.",
    4:  "Tu veux une explication pour tout : très bien, tant que tu n'exiges pas que la tienne soit la seule valable.",
    5:  "Tu t'énerves quand les choses ne vont pas à ton rythme : la vie a le sien, et en général elle vise juste.",
    6:  "Tu sens tout de suite la tension dans l'air : tu peux t'en servir pour te disputer ou pour jouer les médiateurs.",
    7:  "Les gens te suivent quand tu montres le chemin sans donner d'ordres.",
    8:  "Tu fais les choses à ta façon : quand tu te fonds dans la masse pour ne pas te faire remarquer, tu éteins ta meilleure part.",
    9:  "Tu te perds dans les mauvais détails ou tu remets à plus tard : choisis un bon détail et insiste là.",
    10: "Arrête de jouer un personnage : quand tu es simplement toi, les choses se règlent d'elles-mêmes.",
    11: "Tu as la tête pleine d'idées et d'images : tu n'es pas obligé de toutes les réaliser — beaucoup sont là pour être racontées.",
    12: "Parle moins et aux bons moments : une phrase de toi, dite au bon moment, vaut de l'or.",
    13: "Les gens te confient leurs secrets : écoute sans les porter à leur place.",
    14: "L'argent arrive quand tu travailles à ce que tu aimes, pas quand tu serres les dents dans un boulot que tu détestes.",
    15: "Tu vis par vagues : des jours pleins à craquer et des jours vides. C'est ton rythme normal, pas une panne.",
    16: "Tu t'enthousiasmes pour mille choses : choisis-en une et répète-la jusqu'à ce qu'elle devienne un art.",
    17: "Tu vois où les choses vont finir avant les autres : offre ta prévision, sans l'imposer.",
    18: "Tu remarques tout de suite ce qui cloche : sers-t'en pour réparer, pas pour critiquer (toi y compris).",
    19: "Tu sens les besoins des autres avant qu'ils ne parlent : aide sans te rendre indispensable.",
    20: "Tu es doué pour agir sur le vif : fais-le quand c'est utile, pas pour remplir le silence.",
    21: "Tu as besoin de garder le contrôle : ça marche sur les choses, ça étouffe les gens. Apprends à déléguer pour de vrai.",
    22: "Même quand c'est la tempête à l'intérieur, tu arrives à rester doux : c'est ta magie — ne la gâche pas en coups d'éclat.",
    23: "Tu sais expliquer des choses compliquées simplement : dis-le en une phrase et arrête-toi là.",
    24: "Tu rumines en boucle : le déclic arrive dans la pause, pas au tour suivant.",
    25: "Les blessures t'ont fermé le cœur petit à petit : chaque fois que tu acceptes ce qui est, un morceau se rouvre.",
    26: "Tu sais te vendre et vendre : fais-le pour des choses auxquelles tu crois, pas pour gonfler ton image.",
    27: "Tu prends soin de tout le monde : très bien — mais sans tenir le compte des services rendus.",
    28: "Tu préfères risquer plutôt que regretter : mais choisis seulement les mises qui en valent vraiment la peine.",
    29: "Quand tu dis oui, dis-le en entier : les oui à moitié te vident.",
    30: "Tu désires très fort : profite du feu sans attendre que ce que tu désires te sauve la vie.",
    31: "Quand tu parles, le groupe écoute : dis ce que tout le monde ressent mais que personne ne formule.",
    32: "La peur d'échouer te fait tout retenir : distingue ce qui mérite d'être gardé de ce qui doit partir.",
    33: "Après les expériences fortes, tu as besoin de te retirer : c'est là que tu comprends — et ensuite, raconte.",
    34: "Tu as de l'énergie à revendre : mets-la sur ta route, pas à prouver quelque chose à quelqu'un.",
    35: "Tu veux tout essayer : choisis les expériences qui t'apprennent, pas celles qui comblent l'ennui.",
    36: "Tu traverses des tempêtes émotionnelles : chaque crise surmontée fait de toi la personne qui comprend les autres.",
    37: "Tu es le ciment de la famille ou du groupe : des accords clairs et de l'affection, sans tout avaler pour avoir la paix.",
    38: "Tu es un battant né : choisis les combats qui en valent la peine, pas tous.",
    39: "Tu sais piquer là où il faut : provoque pour débloquer, pas pour agacer.",
    40: "Tu travailles dur puis tu t'effondres : apprends à dire non à temps, sans rancune.",
    41: "Tu rêves toujours d'un nouveau départ : transformes-en un en réalité, laisse les autres au rêve.",
    42: "Tu as du mal à clore les chapitres : chaque fin bien fermée te libère pour le début suivant.",
    43: "Tu as des intuitions à contre-courant : traduis-les en mots compréhensibles, sinon elles resteront sans écho.",
    44: "Tu comprends les gens au premier regard : mets-les au bon poste, sans les manipuler.",
    45: "Tu es un chef de meute naturel : dirige en distribuant, pas en accumulant.",
    46: "Tout va mieux quand tu habites ton corps : écoute-le, au lieu de vivre seulement dans ta tête.",
    47: "Les souvenirs lourds te tournent dans la tête : avec le temps ils deviennent ta profondeur — laisse-les mûrir.",
    48: "Tu te sens toujours pas assez prêt : agis quand même — ta profondeur sort sous pression.",
    49: "Tu as tendance à couper les ponts sur un coup de tête : fais tes révolutions au bon moment, en emmenant ceux qui suivent.",
    50: "Tu portes les responsabilités de tout le monde : protège ce qui compte sans t'écraser.",
    51: "Tu es le premier à oser : ton courage ouvre des chemins — puis reviens raconter que c'est possible.",
    52: "Tu vibres d'énergie contenue : concentre-la sur un seul point et lâche le reste.",
    53: "Tu commences mille choses : ce n'est pas à toi de toutes les finir — mais mène-en une jusqu'au bout.",
    54: "Tu es ambitieux : l'envie de monter est saine quand tu montes en niveau, pas seulement en quantité.",
    55: "Ton humeur va par vagues : surfe-les au lieu d'accuser ce qui est dehors. L'humeur est une météo, pas une identité.",
    56: "Tu te disperses dans mille stimulations : transforme-les en récits et elles deviennent une richesse pour tous.",
    57: "Tu sens les choses un instant avant les autres : cet instinct subtil a presque toujours raison — écoute-le tout de suite.",
    58: "Tu vois toujours ce qui peut être amélioré : répare avec joie, au lieu de te plaindre du défaut.",
    59: "Tu vas droit à l'intimité : sans stratégies tu fonctionnes mieux — la transparence désarme.",
    60: "Les limites t'étouffent : accepte leur forme, et à l'intérieur de cette forme tu deviens créatif.",
    61: "Tu cherches des réponses aux grandes questions : apprends à aimer la question — les éclairs viennent tout seuls.",
    62: "Tu es d'une précision extrême : dis exactement ce qu'il faut, pas tout ce que tu sais.",
    63: "Tu doutes de tout : transforme tes soupçons en questions précises et en vérifications, pas en idées fixes.",
    64: "Tu as la tête pleine d'images qui cherchent un sens : arrête de forcer — le tableau se compose tout seul."
  };

  window.HOLO_GLOSS = window.HOLO_GLOSS || {};
  window.HOLO_GLOSS.fr = { ppLbl: "En termes simples", TERMS, PP };
})();
