/* ============================================================
   OLOGENETICA · GLOSARIO — ESPAÑOL
   · TERMS: términos que el lector puede no conocer.
     m = formas a reconocer en el texto (singular/plural/variantes,
         tal como aparecen en los textos de ESTE idioma)
     t = título del bocadillo · d = explicación en lenguaje cotidiano
   · PP: las 64 Llaves «en palabras sencillas» — una línea concreta cada una.
   ============================================================ */
(function () {

  const TERMS = {
    chiave:    { m: ["Llave", "Llaves"], t: "Llave",
      d: "Una de las 64 «energías base» del sistema. Cada Llave corresponde a un hexagrama del I Ching y describe una manera de ser: desde su lado difícil (Sombra) hasta su talento (Don)." },
    ombra:     { m: ["Sombra", "sombras"], t: "Sombra",
      d: "El lado reactivo de una Llave: cómo se comporta esa energía cuando hay miedo o estrés. No es un defecto que haya que eliminar — es el punto de partida de la lectura." },
    dono:      { m: ["Don", "Dones"], t: "Don",
      d: "El talento de la Llave: exactamente la misma energía de la Sombra, pero vivida con consciencia. La Sombra que se relaja se convierte en Don." },
    siddhi:    { m: ["Siddhi"], t: "Siddhi",
      d: "Palabra sánscrita: el florecimiento más alto posible de una Llave, su potencial pleno. Sirve de estrella polar — no es una meta que haya que «alcanzar»." },
    linea:     { m: ["Línea", "Líneas"], t: "Línea",
      d: "Cada Llave se divide en 6 Líneas. Si la Llave es el «qué», la Línea es el «cómo»: estudiando (1), por talento natural (2), a base de intentos (3), a través de las personas (4), resolviendo (5), o con la visión de conjunto (6)." },
    sfera:     { m: ["esfera", "esferas"], t: "Esfera",
      d: "Un área de tu vida: trabajo, relaciones, mente, prosperidad… El perfil tiene 11, y en cada una «cae» una de las 64 Llaves." },
    esagramma: { m: ["hexagrama", "hexagramas"], t: "Hexagrama",
      d: "Figura del I Ching formada por 6 líneas enteras o partidas. Las combinaciones posibles son 64: una por cada Llave." },
    iching:    { m: ["I Ching"], t: "I Ching",
      d: "Antiquísimo libro chino de sabiduría, el «Libro de los Cambios»: describe 64 situaciones-tipo de la vida a través de los 64 hexagramas." },
    natale:    { m: ["natal", "personalidad", "Personalidad"], t: "Natal / Personalidad",
      d: "Se calcula con el momento exacto del nacimiento. Es tu parte consciente: la que reconoces como «yo» y en la que te reconoces sin esfuerzo." },
    design:    { m: ["diseño", "Diseño"], t: "Diseño",
      d: "Se calcula unos 3 meses antes del nacimiento (cuando el Sol estaba 88° más atrás). Es tu parte inconsciente: actúa sola, antes de que tú decidas — a menudo es la que los demás ven mejor que tú." },
    sequenza:  { m: ["Secuencia", "Secuencias", "secuencia", "secuencias"], t: "Secuencia",
      d: "Un recorrido de lectura: las 11 esferas se leen en tres grupos. Activación = tu propósito, Venus = el corazón y las relaciones, Perla = la prosperidad." },
    croce:     { m: ["Cruz de encarnación", "cruz de encarnación"], t: "Cruz de encarnación",
      d: "Los 4 números centrales del perfil: las Llaves del Sol y de la Tierra, conscientes e inconscientes. Es el «tema de fondo» de tu vida resumido en cuatro energías." },
    specchio:  { m: ["socios de programación", "Llaves espejo", "Llave espejo", "espejo"], t: "Llaves espejo",
      d: "Cada Llave tiene una gemela opuesta en la rueda, a 180°. Son dos mitades del mismo tema: lo que le falta a una, lo tiene la otra." },
    anello:    { m: ["anillos de codones", "anillo de codones", "Anillos de codones"], t: "Anillo de codones",
      d: "Las 64 Llaves se agrupan en 21 «familias» llamadas anillos, inspiradas en cómo los codones del ADN se agrupan por función. El vínculo con el ADN es simbólico, no científico." },
    codone:    { m: ["codones", "codón"], t: "Codones",
      d: "Las «piezas» del código genético: tripletas que forman 64 combinaciones posibles — el mismo número que los hexagramas. De ahí el paralelismo simbólico del sistema." },
    ritsolare: { m: ["retorno solar", "Retorno solar"], t: "Retorno solar",
      d: "El instante, cerca de tu cumpleaños, en que el Sol vuelve exactamente a la posición donde estaba cuando naciste. Se usa para leer el tema del año." },
    ritsaturno:{ m: ["retorno de Saturno", "1.er retorno de Saturno", "2.º retorno de Saturno"], t: "Retorno de Saturno",
      d: "Saturno tarda ~29 años en dar la vuelta completa y volver a donde estaba en tu nacimiento. Hacia los 29 y los 59 años: tradicionalmente, dos grandes pasajes de maduración." },
    transito:  { m: ["tránsitos", "tránsito", "transita"], t: "Tránsito",
      d: "Dónde están los planetas ahora mismo, comparado con tu perfil. Cuando un planeta «pasa» sobre una de tus Llaves, ese tema se enciende durante unos días." },
    effemeridi:{ m: ["efemérides", "Efemérides"], t: "Efemérides",
      d: "Las tablas astronómicas con las posiciones exactas de los planetas, momento a momento. Las mismas que usan los observatorios: aquí no hay nada inventado, las posiciones son reales." },
    arco:      { m: ["88° de arco solar", "arco solar"], t: "Arco solar",
      d: "El tramo de círculo que el Sol recorre en el cielo visto desde la Tierra. 88° equivalen a unos 3 meses de camino." },
    ruota:     { m: ["rueda zodiacal", "rueda de los 64"], t: "La rueda",
      d: "El círculo de 360° del zodíaco, dividido en 64 sectores iguales: uno por Llave. La posición de un planeta en el círculo dice en qué Llave se encuentra." },
    qi:        { m: ["IQ"], t: "IQ — el ciclo de la mente",
      d: "La esfera formada entre los 14 y los 21 años: cómo tu mente aprendió a pensar y a defenderse en la adolescencia. De adulto la confundes con «mi manera de razonar»." },
    qe:        { m: ["EQ"], t: "EQ — el ciclo del corazón",
      d: "La esfera formada entre los 7 y los 14 años: cómo tu corazón aprendió a reaccionar de niño. Es la defensa emocional que hoy salta sola." },
    qs:        { m: ["SQ"], t: "SQ — la raíz de la confianza",
      d: "La esfera de los primeros 7 años de vida: la huella más profunda, donde se decidió cuánto se puede confiar en el amor. También llamada «Punto de Amor»." },
    lifework:  { m: ["Life's Work"], t: "Life's Work",
      d: "«La obra de tu vida»: aquello que has venido a hacer, el papel que el mundo ve en ti. Es la esfera principal del perfil." },
    evolution: { m: ["Evolution"], t: "Evolution",
      d: "Tu reto central: el tema que la vida te vuelve a poner delante para hacerte crecer. No es un defecto — es un camino." },
    radiance:  { m: ["Radiance"], t: "Radiance",
      d: "Lo que enciende tu vitalidad y tu salud: cuando lo vives, se nota — literalmente — en la energía que irradias." },
    purposeT:  { m: ["Purpose"], t: "Purpose",
      d: "Tu propósito profundo: se activa cuando lo que haces sirve a algo más grande que tú." },
    attraction:{ m: ["Attraction"], t: "Attraction",
      d: "A quién y qué atraes en las relaciones: la puerta de entrada de tus vínculos." },
    core:      { m: ["Core", "Vocation"], t: "Core / Vocation",
      d: "La herida más antigua (Core) que, una vez atravesada, se convierte en tu vocación (Vocation): el punto donde el dolor se transforma en oficio del alma." },
    culture:   { m: ["Culture"], t: "Culture",
      d: "Tu lugar natural en la comunidad: la aportación que traes cuando formas parte de un grupo." },
    pearl:     { m: ["Pearl", "Brand"], t: "Pearl / Brand",
      d: "La Perla es la recompensa: la prosperidad que llega cuando simplificas. El Brand es cómo te reconoce el mundo — el Life's Work visto desde fuera." },
    ics:       { m: ["ICS", "archivo ICS"], t: "Archivo ICS",
      d: "El formato estándar de los calendarios: descargas el archivo, lo abres y los eventos aparecen en tu calendario (Google Calendar, Apple, Outlook…)." }
  };

  // Las 64 Llaves en palabras sencillas: una línea concreta, cotidiana
  const PP = {
    1:  "Tienes días en blanco en los que no creas nada: déjalos pasar en vez de pelearte con ellos, y vuelves con ideas frescas.",
    2:  "Sabes por instinto qué dirección tomar: fíate de esa brújula en vez de pedir confirmación a todo el mundo.",
    3:  "Al principio lo lías todo, y luego encuentras soluciones que nadie había visto: el desorden es tu materia prima.",
    4:  "Quieres una explicación para todo: estupendo, mientras no pretendas que la tuya sea la única válida.",
    5:  "Te pones nervioso si las cosas no van a tu ritmo: la vida tiene el suyo, y casi siempre acierta.",
    6:  "Notas enseguida la tensión en el ambiente: puedes usarla para discutir o para hacer de mediador.",
    7:  "La gente te sigue cuando señalas el camino sin dar órdenes.",
    8:  "Haces las cosas a tu manera: cuando te uniformas para no llamar la atención, apagas tu mejor parte.",
    9:  "Te pierdes en los detalles equivocados o lo dejas para luego: elige un detalle que importe e insiste ahí.",
    10: "Deja de interpretar un personaje: cuando eres simplemente tú, las cosas se ordenan solas.",
    11: "Tienes la cabeza llena de ideas e imágenes: no hace falta realizarlas todas — muchas son para contarlas.",
    12: "Habla menos y en los momentos justos: una frase tuya dicha a tiempo vale oro.",
    13: "La gente te cuenta sus secretos: escucha sin cargar con ellos.",
    14: "El dinero llega cuando trabajas en lo que amas, no cuando aprietas los dientes en un trabajo que detestas.",
    15: "Vives por oleadas: días llenísimos y días vacíos. Es tu ritmo normal, no una avería.",
    16: "Te entusiasmas con mil cosas: elige una y repítela hasta que se convierta en arte.",
    17: "Ves adónde irán a parar las cosas antes que los demás: ofrece la previsión, sin imponerla.",
    18: "Notas al instante lo que falla: úsalo para arreglar, no para criticar (a ti incluido).",
    19: "Sientes las necesidades de los demás antes de que hablen: ayuda sin volverte imprescindible.",
    20: "Se te da bien actuar sobre la marcha: hazlo cuando haga falta, no para llenar el silencio.",
    21: "Necesitas tener el control: funciona con las cosas, ahoga con las personas. Aprende a delegar de verdad.",
    22: "Incluso cuando por dentro hay tormenta consigues seguir siendo amable: es tu magia — no la malgastes en arrebatos.",
    23: "Sabes explicar cosas complicadas de forma sencilla: dilo en una frase y párate ahí.",
    24: "Le das vueltas a todo en bucle: el giro llega en la pausa, no en la vuelta siguiente.",
    25: "Las heridas te han ido cerrando el corazón a plazos: cada vez que aceptas lo que hay, se reabre un trozo.",
    26: "Sabes venderte y vender: úsalo para cosas en las que crees, no para inflar la imagen.",
    27: "Cuidas de todo el mundo: muy bien — pero sin llevar la cuenta de los favores.",
    28: "Prefieres arriesgarte a arrepentirte: eso sí, elige solo las apuestas que valen de verdad.",
    29: "Cuando digas que sí, dilo entero: los síes a medias te dejan vacío.",
    30: "Deseas con muchísima fuerza: disfruta del fuego sin esperar que lo que deseas te salve la vida.",
    31: "Cuando hablas, el grupo escucha: di lo que todos sienten pero nadie formula.",
    32: "El miedo a fracasar te hace retenerlo todo: distingue lo que hay que conservar de lo que hay que soltar.",
    33: "Después de las experiencias fuertes necesitas retirarte: ahí es donde entiendes — y luego cuéntalo.",
    34: "Tienes energía para dar y regalar: úsala para tu camino, no para demostrarle nada a nadie.",
    35: "Quieres probarlo todo: elige las experiencias que enseñan, no las que rellenan el aburrimiento.",
    36: "Atraviesas tormentas emocionales: cada crisis superada te convierte en la persona que entiende a los demás.",
    37: "Eres el pegamento de la familia o del grupo: pactos claros y cariño, sin tragar sapos por tener la fiesta en paz.",
    38: "Eres un luchador nato: elige las batallas que valen la pena, no todas.",
    39: "Sabes pinchar donde hace falta: provoca para desbloquear, no para irritar.",
    40: "Trabajas duro y luego te derrumbas: aprende a decir no a tiempo, sin rencor.",
    41: "Sueñas siempre con un nuevo comienzo: convierte uno en un hecho, y el resto déjalo soñar.",
    42: "Te cuesta cerrar capítulos: cada final bien cerrado te libera para el comienzo siguiente.",
    43: "Tienes intuiciones que se salen del coro: tradúcelas a palabras comprensibles, o se quedarán sin oír.",
    44: "Calas a las personas a la primera: ponlas en el papel adecuado, sin manejarlas.",
    45: "Eres un líder de manada natural: guía repartiendo, no acumulando.",
    46: "Te va bien cuando habitas tu cuerpo: escúchalo, en vez de vivir solo de cabeza.",
    47: "Los recuerdos pesados te dan vueltas en la cabeza: con el tiempo se convierten en tu profundidad — déjalos madurar.",
    48: "Sientes que nunca estás lo bastante preparado: actúa igualmente — tu profundidad sale bajo presión.",
    49: "Tiendes a cortar por lo sano de golpe: haz las revoluciones en el momento justo, llevándote a quien se apunte.",
    50: "Cargas con las responsabilidades de todos: cuida lo que importa sin aplastarte.",
    51: "Eres el primero que se atreve: tu valentía abre caminos — luego vuelve a contar que se puede.",
    52: "Vibras de energía contenida: concéntrala en un solo punto y suelta el resto.",
    53: "Empiezas mil cosas: no todas te tocan a ti terminarlas — pero una llévala hasta el final.",
    54: "Eres ambicioso: el impulso de subir es sano cuando subes de nivel, no solo de cantidad.",
    55: "Tu ánimo va por olas: cabálgalas en vez de echarle la culpa a lo de fuera. El ánimo es meteorología, no identidad.",
    56: "Te distraes con mil estímulos: conviértelos en relatos y se vuelven riqueza para todos.",
    57: "Sientes las cosas un instante antes que los demás: ese instinto sutil casi siempre acierta — escúchalo al momento.",
    58: "Siempre ves lo que se puede mejorar: arregla con alegría, en vez de lamentarte del defecto.",
    59: "Vas directo a la intimidad: sin estrategias funcionas mejor — la transparencia desarma.",
    60: "Los límites se te quedan pequeños: acepta su forma, y dentro de esa forma te vuelves creativo.",
    61: "Buscas respuestas a las grandes preguntas: aprende a amar la pregunta — los destellos llegan solos.",
    62: "Eres precisísimo: di exactamente lo que hace falta, no todo lo que sabes.",
    63: "Dudas de todo: convierte las sospechas en preguntas concretas y comprobaciones, no en carcoma.",
    64: "Tienes la cabeza llena de imágenes que buscan un sentido: deja de forzar — el cuadro se compone solo."
  };

  window.HOLO_GLOSS = window.HOLO_GLOSS || {};
  window.HOLO_GLOSS.es = { ppLbl: "En palabras sencillas", TERMS, PP };
})();
