/* ============================================================
   OLOGENETICA · GLOSSARY — ENGLISH
   · TERMS: words a reader may not know.
     m = surface forms to match in the texts of THIS language
         (singular/plural/variants as they actually appear)
     t = tooltip title · d = plain-language explanation
   · PP: the 64 Keys "in plain words" — one concrete line each.
   ============================================================ */
(function () {

  const TERMS = {
    chiave:    { m: ["Key", "Keys"], t: "Key",
      d: "One of the 64 “base energies” of the system. Each Key matches a hexagram of the I Ching and describes a way of being: from its difficult side (Shadow) to its talent (Gift)." },
    ombra:     { m: ["Shadow", "shadows"], t: "Shadow",
      d: "The reactive side of a Key: how that energy behaves when fear or stress takes over. It's not a flaw to get rid of — it's the starting point of the reading." },
    dono:      { m: ["Gift", "Gifts"], t: "Gift",
      d: "The talent of the Key: exactly the same energy as the Shadow, lived with awareness. A Shadow that relaxes becomes a Gift." },
    siddhi:    { m: ["Siddhi"], t: "Siddhi",
      d: "A Sanskrit word: the highest possible flowering of a Key, its full potential. It works as a north star — not a goal to “achieve”." },
    linea:     { m: ["Line", "Lines"], t: "Line",
      d: "Each Key splits into 6 Lines. If the Key is the “what”, the Line is the “how”: through study (1), natural talent (2), trial and error (3), through people (4), by solving things (5), or with the big picture (6)." },
    sfera:     { m: ["sphere", "spheres"], t: "Sphere",
      d: "An area of your life: work, relationships, mind, prosperity… The profile has 11 of them, and one of the 64 Keys “lands” in each." },
    esagramma: { m: ["hexagram", "hexagrams"], t: "Hexagram",
      d: "A figure from the I Ching made of 6 solid or broken lines. There are 64 possible combinations: one for each Key." },
    iching:    { m: ["I Ching"], t: "I Ching",
      d: "An ancient Chinese book of wisdom, the “Book of Changes”: it describes 64 archetypal life situations through the 64 hexagrams." },
    natale:    { m: ["natal", "personality", "Personality"], t: "Natal / Personality",
      d: "Calculated for the exact moment of your birth. It's your conscious side: the part you recognise as “me” and identify with easily." },
    design:    { m: ["design", "Design"], t: "Design",
      d: "Calculated about 3 months before birth (when the Sun was 88° further back). It's your unconscious side: it acts on its own, before you decide — often it's what other people see in you better than you do." },
    sequenza:  { m: ["Sequence", "Sequences", "sequence", "sequences"], t: "Sequence",
      d: "A reading path: the 11 spheres are read in three groups. Activation = your purpose, Venus = the heart and relationships, Pearl = prosperity." },
    croce:     { m: ["Incarnation Cross", "incarnation cross"], t: "Incarnation Cross",
      d: "The 4 central numbers of the profile: the Keys of Sun and Earth, conscious and unconscious. It's the “central theme” of your life summed up in four energies." },
    specchio:  { m: ["programming partners", "mirror Keys", "mirror Key", "mirror keys", "mirror"], t: "Mirror Keys",
      d: "Every Key has an opposite twin on the wheel, 180° away. They're two halves of the same theme: what one lacks, the other has." },
    anello:    { m: ["codon rings", "codon ring", "Codon rings"], t: "Codon ring",
      d: "The 64 Keys group into 21 “families” called rings, inspired by the way DNA codons group by function. The link with DNA is symbolic, not scientific." },
    codone:    { m: ["codons", "codon"], t: "Codons",
      d: "The “building blocks” of the genetic code: triplets that form 64 possible combinations — the same number as the hexagrams. That's where the system's symbolic parallel comes from." },
    ritsolare: { m: ["solar return", "Solar return"], t: "Solar return",
      d: "The moment, close to your birthday, when the Sun comes back to exactly where it was when you were born. It's used to read the theme of the year ahead." },
    ritsaturno:{ m: ["Saturn return", "1st Saturn return", "2nd Saturn return"], t: "Saturn return",
      d: "Saturn takes about 29 years to complete a full loop and come back to where it was at your birth. Around 29 and 59: traditionally two great rites of maturing." },
    transito:  { m: ["transits", "transit"], t: "Transit",
      d: "Where the planets are right now, compared with your profile. When a planet “passes over” one of your Keys, that theme lights up for a few days." },
    effemeridi:{ m: ["ephemerides", "Ephemerides"], t: "Ephemerides",
      d: "The astronomical tables with the exact positions of the planets, moment by moment. The same ones observatories use: nothing here is made up, the positions are real." },
    arco:      { m: ["88° of solar arc", "solar arc", "88° of arc"], t: "Solar arc",
      d: "The stretch of circle the Sun travels across the sky as seen from Earth. 88° corresponds to roughly 3 months of its journey." },
    ruota:     { m: ["zodiac wheel", "wheel of the 64", "wheel of 64"], t: "The wheel",
      d: "The 360° circle of the zodiac, divided into 64 equal sectors: one per Key. A planet's position on the circle tells you which Key it sits in." },
    qi:        { m: ["IQ"], t: "IQ — the cycle of the mind",
      d: "The sphere shaped between ages 14 and 21: how your mind learned to think and defend itself in adolescence. As an adult you mistake it for “the way I reason”." },
    qe:        { m: ["EQ"], t: "EQ — the cycle of the heart",
      d: "The sphere shaped between ages 7 and 14: how your heart learned to react as a child. It's the emotional defence that still fires on its own today." },
    qs:        { m: ["SQ"], t: "SQ — the root of trust",
      d: "The sphere of your first 7 years of life: the deepest imprint, where it was decided how much love can be trusted. Also called the “Point of Love”." },
    lifework:  { m: ["Life's Work"], t: "Life's Work",
      d: "What you came here to do, the role the world sees in you. It's the main sphere of the profile." },
    evolution: { m: ["Evolution"], t: "Evolution",
      d: "Your central challenge: the theme life keeps bringing back to make you grow. Not a flaw — a path." },
    radiance:  { m: ["Radiance"], t: "Radiance",
      d: "What switches on your vitality and health: when you live it, it shows — literally — in the energy you give off." },
    purposeT:  { m: ["Purpose"], t: "Purpose",
      d: "Your deep purpose: it activates when what you do serves something bigger than you." },
    attraction:{ m: ["Attraction"], t: "Attraction",
      d: "Who and what you attract in relationships: the doorway into your bonds." },
    core:      { m: ["Core", "Vocation"], t: "Core / Vocation",
      d: "Your oldest wound (Core) which, once crossed, becomes your calling (Vocation): the point where pain turns into the soul's trade." },
    culture:   { m: ["Culture"], t: "Culture",
      d: "Your natural place in the community: the contribution you bring when you're part of a group." },
    pearl:     { m: ["Pearl", "Brand"], t: "Pearl / Brand",
      d: "The Pearl is the reward: the prosperity that arrives when you simplify. The Brand is how the world recognises you — your Life's Work seen from the outside." },
    ics:       { m: ["ICS file", "ICS"], t: "ICS file",
      d: "The standard calendar format: download the file, open it, and the events appear in your calendar (Google Calendar, Apple, Outlook…)." }
  };

  // The 64 Keys in plain words: one concrete, everyday line each
  const PP = {
    1:  "You have off days when nothing comes: let them pass instead of fighting them, and you come back with fresh ideas.",
    2:  "You instinctively know which way to go: trust that compass instead of asking everyone for reassurance.",
    3:  "You start out in a mess, then find solutions nobody else saw: disorder is your raw material.",
    4:  "You want an explanation for everything: great, as long as you don't insist yours is the only right one.",
    5:  "You get edgy when things don't run on your schedule: life has its own timing, and it's usually right.",
    6:  "You feel tension in the air instantly: you can use it to pick fights or to make peace.",
    7:  "People follow you when you point the way without giving orders.",
    8:  "You do things your own way: when you blend in to avoid standing out, you switch off your best part.",
    9:  "You get lost in the wrong details or keep putting things off: pick one detail that matters and stay on it.",
    10: "Stop playing a character: when you're simply yourself, things sort themselves out.",
    11: "Your head is full of ideas and images: you don't have to build them all — many are there to be told.",
    12: "Speak less, and at the right moments: one sentence of yours, said at the right time, is worth gold.",
    13: "People tell you their secrets: listen without carrying them for them.",
    14: "Money comes when you work at what you love, not when you grit your teeth through a job you hate.",
    15: "You live in waves: packed days and empty days. That's your normal rhythm, not a malfunction.",
    16: "You get excited about a thousand things: pick one and repeat it until it becomes an art.",
    17: "You see where things are heading before other people do: offer the forecast without forcing it.",
    18: "You spot what's wrong straight away: use it to fix things, not to criticise (yourself included).",
    19: "You sense other people's needs before they speak: help without making yourself indispensable.",
    20: "You're good at acting on the spot: do it when it's needed, not to fill the silence.",
    21: "You need to be in control: it works on things, it suffocates people. Learn to truly delegate.",
    22: "Even when there's a storm inside, you manage to stay kind: that's your magic — don't waste it on outbursts.",
    23: "You can explain complicated things simply: say it in one sentence and stop there.",
    24: "You ruminate in loops: the breakthrough comes in the pause, not in the next lap.",
    25: "Old wounds closed your heart bit by bit: every time you accept what's here, a piece of it reopens.",
    26: "You know how to sell — yourself included: use it for things you believe in, not to inflate the image.",
    27: "You look after everyone: fine — but stop keeping score of the favours.",
    28: "You'd rather take the risk than live with the regret: just pick only the stakes that are truly worth it.",
    29: "When you say yes, say it all the way: half-yeses drain you.",
    30: "You desire intensely: enjoy the fire without expecting what you long for to save your life.",
    31: "When you speak, the group listens: say what everyone feels but nobody puts into words.",
    32: "Fear of failing makes you hold on to everything: learn to tell what's worth keeping from what's ready to go.",
    33: "After intense experiences you need to withdraw: that's where you understand — then come back and tell the story.",
    34: "You have energy to spare: spend it on your own path, not on proving something to someone.",
    35: "You want to try everything: choose the experiences that teach you something, not the ones that just fill the boredom.",
    36: "You go through emotional storms: every crisis you cross makes you the person who understands others.",
    37: "You're the glue of the family or the group: clear agreements and affection, without swallowing things for the sake of peace.",
    38: "You're a born fighter: choose the battles that matter, not all of them.",
    39: "You know exactly where to poke: provoke to unblock, not to irritate.",
    40: "You work hard and then crash: learn to say no in time, without resentment.",
    41: "You're always dreaming of a fresh start: turn one into a fact, and let the rest stay dreams.",
    42: "You struggle to close chapters: every ending done properly frees you for the next beginning.",
    43: "You have insights nobody else has: translate them into plain words, or they'll go unheard.",
    44: "You read people at first glance: put them in the right role, without manoeuvring them.",
    45: "You're a natural pack leader: lead by distributing, not by hoarding.",
    46: "Things go well when you inhabit your body: listen to it, instead of living only in your head.",
    47: "Heavy memories keep circling in your head: with time they become your depth — let them ripen.",
    48: "You never feel ready enough: act anyway — your depth comes out under pressure.",
    49: "You tend to burn bridges on impulse: make your revolutions at the right moment, taking along whoever's in.",
    50: "You shoulder everyone's responsibilities: guard what matters without crushing yourself.",
    51: "You're the first to dare: your courage opens roads — then come back and tell people it can be done.",
    52: "You hum with pent-up energy: focus it on one single point and let go of the rest.",
    53: "You start a thousand things: not all of them are yours to finish — but carry one all the way through.",
    54: "You're ambitious: the drive to climb is healthy when you level up, not just pile up.",
    55: "Your mood moves in waves: ride them instead of blaming what's outside. Mood is weather, not identity.",
    56: "A thousand stimuli distract you: turn them into stories and they become riches for everyone.",
    57: "You sense things a beat before everyone else: that subtle instinct is almost always right — listen to it straight away.",
    58: "You always see what could be improved: fix it with joy, instead of complaining about the flaw.",
    59: "You go straight to intimacy: you work better without strategies — transparency disarms.",
    60: "Limits feel tight on you: accept their shape, and inside that shape you become creative.",
    61: "You chase answers to the big questions: learn to love the question — the flashes arrive on their own.",
    62: "You're extremely precise: say exactly what's needed, not everything you know.",
    63: "You doubt everything: turn suspicions into precise questions and checks, not into worms in your head.",
    64: "Your head is full of images looking for a meaning: stop forcing it — the picture assembles itself."
  };

  window.HOLO_GLOSS = window.HOLO_GLOSS || {};
  window.HOLO_GLOSS.en = { ppLbl: "In plain words", TERMS, PP };
})();
